version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
    volumes:
      - kafka-data:/kafka
    networks:
      - kafka-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-net

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-net

  airflow:
    image: apache/airflow:2.2.4
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__SQL_ALCHEMY__DATABASE_URI: mysql://user:userpass@mysql/example_db
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    ports:
      - "8080:8080"
    volumes:
      - airflow-data:/usr/local/airflow
    networks:
      - airflow-net

volumes:
  zookeeper-data:
  kafka-data:
  mongodb-data:
  mysql-data:
  airflow-data:

networks:
  kafka-net:
  mongo-net:
  mysql-net:
  airflow-net: